on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push for Signifi.org
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: wp.signifi.org
        username: signifi
        password: ${{ secrets.SIGNIFI_SFTP_PASSWORD }}
        exclude:
          - documentation.md
          - doc.docx